[package]
name = "p2d"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.6"
pest_derive = "2.6"
bimap = "0.6"

[features]
show_progress = []
cache = []
disconnected_components = []

default = ["show_progress", "cache", "disconnected_components"]